### PR TITLE
Bugfix: Fix 'Extension Bugs' link in popup

### PR DESCRIPTION
**Pull request by rummik**
Pointed at a nonexistent URL before.  (https://github.com/Habitica/habitica-chrome/)

### CODE REVIEW

**Comment by brazilianldsjaguar** [comment]
Hah, was totally just thrown by this. Please merge soon! :D

**Comment by paglias** [comment]
Sorry for the delay @rummik, I totally missed this!

**Comment by paglias** [comment]
@rummik if you give me your UUID on Habitica I'll award you a contributor badge for the PR, thanks :)

**Comment by rummik** [comment]
@paglias 3854b00b-350c-4ec2-9818-4ec07ac22ad7

**Comment by paglias** [comment]
Tier awarded, thanks!

**Pull request merged**
