### PR TITLE
fixes "Remaining time until sending" time format and label.

### LINKED ISSUE #111: Timer set to send information every 19 hours?
For some reason the timer is set to send information (from what looks to me like) every 19 hours? Is this correct, is there a ways to change that?

Thanks

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/6252099-timer-set-to-send-information-every-19-hours?utm_campaign=plugin&utm_content=tracker%2F85447&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85447&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by p4ul**
Fixes #111 

* Changed wording from "Remaining time until sending" to "Next upload in"
* Fixed countdown timer to show paded  minutes and seconds instead of a random hours, minutes, seconds. Examples 00:32, 01:09, 25:00

### CODE REVIEW

**Comment by paglias** [comment]
@p4ul thanks! if you provide me with your User ID I'll award a badge

**Comment by p4ul** [comment]
Thanks! its the same "P4ul"

**Comment by paglias** [comment]
Sorry, I didn't explain. the user Id is not the username, you can find it
in Setting->User Id
Il 08/gen/2015 22:52 "Paul" <notifications@github.com> ha scritto:

**Comment by p4ul** [comment]
no worries it is 
 50099124-41fb-4d5f-aa36-2e71fa6c0222

**Comment by paglias** [comment]
@p4ul badge awarded

**Pull request merged**
