### PR TITLE
Out-of-box build / jshint / english fixes

### PR DESCRIPTION
**Pull request by brazilianldsjaguar**
Cloned this and had several errors just getting it to build. These are the changes I had to make in order to make things work. A special English fix just for the fun of it.

### CODE REVIEW

**Comment by paglias** [comment]
@brazilianldsjaguar thanks! If you give me your UUID on Habitica I'll award you a contributor badge

**Comment by brazilianldsjaguar** [comment]
Hey @paglias ! Hah, honestly never thought this would get merged. Sweet! Anyway, the user ID is 844ce8f1-fa32-4b7b-8544-f071ded57ba1 and username is brazilianldsjaguar. Thanks!

**Comment by brazilianldsjaguar** [comment]
My goal for the clone, however, is to solve the multi-level domain. but it's a bit harder than I thought. Initially I wanted to solve for 'developers.facebook.com' vs 'facebook.com', but it runs into the same problem as 'google.com.br' (but, apparently, not google.co.uk :smiley: )

**Comment by paglias** [comment]
@brazilianldsjaguar yeah we're not actively improving the Chrome app but contributions are welcome and I'll try to merge them as soon as possible!

**Pull request merged**
